# este es un flujo de trabajo b√°sico

name: primer Flujo de trabajo basico
on: workflow_dispatch
jobs:
  basico-1:
    runs-on: ubuntu-latest
    steps:
      - name: saludo 
        run: echo "hello world"
      - name: despedida
        run: echo "Adios!!"
